# Generated by Django 3.0.5 on 2020-12-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201230_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='forms',
            new_name='Stforms',
        ),
    ]
