# Generated by Django 3.0.5 on 2021-01-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201230_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='stforms',
            name='course',
            field=models.CharField(default='', max_length=10),
        ),
    ]
